In [1]:
import numpy as np
import pandas as pd

In [2]:
loaded = np.load('600k_data.npz')

In [3]:
loaded.files

['arr_0']

In [4]:
#extract train dataset
Train_Data = loaded['arr_0']

In [5]:
Train_Data.shape

(600000, 2382)

In [6]:
Train_Data_df = pd.DataFrame(Train_Data)

In [7]:
#loading the features names

feature_names = np.genfromtxt("ember_2381_feature_names.txt", delimiter=",", dtype='str', comments="!#", invalid_raise=False)

In [8]:
feature_names_df = pd.DataFrame(feature_names)

In [9]:
feature_names_df

                                          0
0                          ByteHistorgram-0
1                          ByteHistorgram-1
2                          ByteHistorgram-2
3                          ByteHistorgram-3
4                          ByteHistorgram-4
...                                     ...
2377          size of data directories - 13
2378  virtual size of data directories - 13
2379          size of data directories - 14
2380  virtual size of data directories - 14
2381                                 labels

[2382 rows x 1 columns]

In [10]:
Train_Data_df.head()

,0,1,2,3,4,5,6,7,8,9,...,2372,2373,2374,2375,2376,2377,2378,2379,2380,2381
0,0.014676,0.004222,0.003923,0.004029,0.004007,0.003775,0.003825,0.003887,0.004153,0.003804,...,35240.0,0.0,0.0,660.0,32768.0,0.0,0.0,0.0,0.0,0.0
1,0.184524,0.031308,0.005693,0.005959,0.008144,0.003512,0.005786,0.008550,0.009141,0.001791,...,92936.0,408.0,608.0,2604.0,4096.0,224.0,442296.0,0.0,0.0,0.0
2,0.251737,0.014205,0.006841,0.008556,0.023493,0.002858,0.003401,0.008556,0.010215,0.001176,...,0.0,0.0,0.0,1120.0,4096.0,192.0,37280.0,0.0,0.0,0.0
3,0.008964,0.004055,0.003925,0.003936,0.004037,0.003878,0.003847,0.003946,0.003939,0.003834,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.020401,0.005213,0.004519,0.004097,0.004240,0.004029,0.003785,0.004593,0.004875,0.003780,...,0.0,0.0,0.0,520.0,4096.0,0.0,0.0,0.0,0.0,0.0

In [11]:
Train_Data_df.columns = feature_names_df

In [12]:
nan_count_Train_Data_df = Train_Data_df.isna().sum()

In [13]:
nan_count_Train_Data_df

(ByteHistorgram-0,)                         0
(ByteHistorgram-1,)                         0
(ByteHistorgram-2,)                         0
(ByteHistorgram-3,)                         0
(ByteHistorgram-4,)                         0
                                           ..
(size of data directories - 13,)            0
(virtual size of data directories - 13,)    0
(size of data directories - 14,)            0
(virtual size of data directories - 14,)    0
(labels,)                                   0
Length: 2382, dtype: int64

In [14]:
sum_nan_count_Train_Data_df = Train_Data_df.isna().sum().sum()

In [15]:
sum_nan_count_Train_Data_df

0

In [16]:
Train_Data_df.describe()

,"(ByteHistorgram-0,)","(ByteHistorgram-1,)","(ByteHistorgram-2,)","(ByteHistorgram-3,)","(ByteHistorgram-4,)","(ByteHistorgram-5,)","(ByteHistorgram-6,)","(ByteHistorgram-7,)","(ByteHistorgram-8,)","(ByteHistorgram-9,)",...,"(virtual size of data directories - 10,)","(size of data directories - 11,)","(virtual size of data directories - 11,)","(size of data directories - 12,)","(virtual size of data directories - 12,)","(size of data directories - 13,)","(virtual size of data directories - 13,)","(size of data directories - 14,)","(virtual size of data directories - 14,)","(labels,)"
count,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,...,6.000000e+05,6.000000e+05,6.000000e+05,6.000000e+05,6.000000e+05,6.000000e+05,6.000000e+05,6.000000e+05,6.000000e+05,600000.0
mean,0.212199,0.011523,0.007162,0.005869,0.008078,0.004157,0.004928,0.003518,0.006470,0.003113,...,6.264353e+05,3.207719e+05,1.199334e+05,7.576417e+03,8.435508e+05,4.201732e+05,7.067874e+05,8.676840e+05,2.218196e+05,0.5
std,0.180596,0.011752,0.007483,0.007711,0.012016,0.005418,0.007134,0.003516,0.004845,0.004913,...,3.480762e+07,3.026381e+07,1.433825e+07,4.908165e+06,4.036399e+07,3.855330e+07,4.052604e+07,4.163358e+07,2.037053e+07,0.5
min,0.000104,0.000001,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0
25%,0.080163,0.004912,0.003834,0.003468,0.004034,0.002538,0.002309,0.002035,0.003802,0.001721,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0
50%,0.169621,0.008650,0.005253,0.004630,0.006180,0.003791,0.003648,0.003350,0.005448,0.002714,...,0.000000e+00,0.000000e+00,0.000000e+00,2.120000e+02,8.192000e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.5
75%,0.282020,0.014275,0.007838,0.006695,0.009899,0.004954,0.004795,0.004043,0.008675,0.003859,...,4.159200e+04,0.000000e+00,0.000000e+00,6.800000e+02,1.679360e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0
max,0.999956,0.859942,0.638846,0.482176,0.386876,0.949696,0.361418,0.549687,0.747807,0.417935,...,3.590280e+09,4.278220e+09,3.787571e+09,3.800990e+09,3.914422e+09,3.771926e+09,4.106158e+09,3.758096e+09,4.099570e+09,1.0

In [17]:
Train_Data_df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
599995    False
599996    False
599997    False
599998    False
599999    False
Length: 600000, dtype: bool

In [18]:
#Dataframe information

Train_Data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600000 entries, 0 to 599999
Columns: 2382 entries, ('ByteHistorgram-0',) to ('labels',)
dtypes: float32(2382)
memory usage: 5.3 GB