In [1]:
import numpy as np
import pandas as pd

In [2]:
loaded = np.load('30k_data.npz')

In [3]:
loaded.files

['arr_0']

In [4]:
#extract train dataset
Train_Data = loaded['arr_0']

In [6]:
Train_Data.shape

(30000, 2382)

In [7]:
Train_Data_df = pd.DataFrame(Train_Data)

In [8]:
#loading the features names

feature_names = np.genfromtxt("ember_2381_feature_names.txt", delimiter=",", dtype='str', comments="!#", invalid_raise=False)

In [10]:
feature_names_df = pd.DataFrame(feature_names)

In [11]:
feature_names_df

                                          0
0                          ByteHistorgram-0
1                          ByteHistorgram-1
2                          ByteHistorgram-2
3                          ByteHistorgram-3
4                          ByteHistorgram-4
...                                     ...
2377          size of data directories - 13
2378  virtual size of data directories - 13
2379          size of data directories - 14
2380  virtual size of data directories - 14
2381                                 labels

[2382 rows x 1 columns]

In [12]:
Train_Data_df.head()

,0,1,2,3,4,5,6,7,8,9,...,2372,2373,2374,2375,2376,2377,2378,2379,2380,2381
0,0.008964,0.004055,0.003925,0.003936,0.004037,0.003878,0.003847,0.003946,0.003939,0.003834,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.009545,0.004028,0.003955,0.004010,0.004088,0.003880,0.003937,0.003876,0.003878,0.003784,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.011696,0.004049,0.003916,0.003979,0.004125,0.003820,0.003907,0.003991,0.003991,0.003873,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.326102,0.035924,0.005441,0.003697,0.006627,0.003836,0.001186,0.004534,0.003976,0.001535,...,4792.0,128.0,584.0,360.0,4096.0,0.0,0.0,0.0,0.0,0.0
4,0.313102,0.010863,0.004468,0.007759,0.006943,0.003184,0.002033,0.002074,0.010033,0.001311,...,0.0,32.0,576.0,340.0,74108.0,0.0,0.0,0.0,0.0,0.0

In [13]:
Train_Data_df.columns = feature_names_df

In [14]:
nan_count_Train_Data_df = Train_Data_df.isna().sum()

In [15]:
nan_count_Train_Data_df

(ByteHistorgram-0,)                         0
(ByteHistorgram-1,)                         0
(ByteHistorgram-2,)                         0
(ByteHistorgram-3,)                         0
(ByteHistorgram-4,)                         0
                                           ..
(size of data directories - 13,)            0
(virtual size of data directories - 13,)    0
(size of data directories - 14,)            0
(virtual size of data directories - 14,)    0
(labels,)                                   0
Length: 2382, dtype: int64

In [16]:
sum_nan_count_Train_Data_df = Train_Data_df.isna().sum().sum()

In [17]:
sum_nan_count_Train_Data_df

0

In [18]:
Train_Data_df.describe()

,"(ByteHistorgram-0,)","(ByteHistorgram-1,)","(ByteHistorgram-2,)","(ByteHistorgram-3,)","(ByteHistorgram-4,)","(ByteHistorgram-5,)","(ByteHistorgram-6,)","(ByteHistorgram-7,)","(ByteHistorgram-8,)","(ByteHistorgram-9,)",...,"(virtual size of data directories - 10,)","(size of data directories - 11,)","(virtual size of data directories - 11,)","(size of data directories - 12,)","(virtual size of data directories - 12,)","(size of data directories - 13,)","(virtual size of data directories - 13,)","(size of data directories - 14,)","(virtual size of data directories - 14,)","(labels,)"
count,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,...,3.000000e+04,3.000000e+04,3.000000e+04,3.000000e+04,3.000000e+04,3.000000e+04,3.000000e+04,3.000000e+04,3.000000e+04,30000.000000
mean,0.212303,0.011434,0.007199,0.005869,0.008074,0.004145,0.004938,0.003536,0.006514,0.003107,...,1.013632e+06,5.963064e+05,2.386559e+05,1.277142e+05,1.354756e+06,9.553215e+05,1.266865e+06,1.107403e+06,4.720599e+05,0.498633
std,0.178738,0.010341,0.008181,0.007722,0.011814,0.004824,0.007466,0.004075,0.004674,0.005006,...,4.860873e+07,3.683733e+07,2.307105e+07,2.194507e+07,6.120849e+07,5.905265e+07,6.135877e+07,4.190967e+07,3.191455e+07,0.500010
min,0.000657,0.000002,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
25%,0.081697,0.004976,0.003841,0.003468,0.004036,0.002538,0.002312,0.002037,0.003795,0.001725,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
50%,0.169574,0.008700,0.005294,0.004630,0.006219,0.003790,0.003642,0.003345,0.005467,0.002701,...,0.000000e+00,0.000000e+00,0.000000e+00,2.080000e+02,8.192000e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
75%,0.283767,0.014266,0.007938,0.006704,0.009899,0.004942,0.004802,0.004043,0.008736,0.003844,...,4.096000e+04,0.000000e+00,0.000000e+00,6.760000e+02,1.720320e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000
max,0.999859,0.312668,0.514253,0.379112,0.372663,0.306854,0.327214,0.313552,0.215537,0.302584,...,2.986345e+09,3.027564e+09,3.787571e+09,3.800990e+09,3.914422e+09,3.771926e+09,3.823243e+09,1.920228e+09,4.099570e+09,1.000000