In [1]:
import numpy as np

filename = 'bodmas.npz'
data = np.load(filename)
X = data['X']  # all the feature vectors
y = data['y']  # labels, 0 as benign, 1 as malicious

print(X.shape, y.shape)

(134435, 2381) (134435,)

In [2]:
import pandas as pd

In [3]:
df1 = pd.DataFrame(X)

df1

,0,1,2,3,4,5,6,7,8,9,...,2371,2372,2373,2374,2375,2376,2377,2378,2379,2380
0,0.056742,0.008017,0.007762,0.005466,0.007762,0.004446,0.005430,0.003061,0.009475,0.006305,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.007062,0.004500,0.004498,0.004318,0.004410,0.004330,0.004265,0.004068,0.004391,0.004306,...,0.0,0.0,0.0,0.0,120.0,16564.0,0.0,0.0,0.0,0.0
2,0.020975,0.004699,0.004002,0.004419,0.004214,0.003865,0.003973,0.004297,0.003921,0.004145,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.006482,0.003821,0.003788,0.003866,0.003734,0.003784,0.003884,0.003937,0.003805,0.003809,...,0.0,0.0,0.0,0.0,140.0,16384.0,0.0,0.0,0.0,0.0
4,0.022135,0.003972,0.003834,0.003869,0.003759,0.003765,0.003777,0.003863,0.003773,0.003798,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134430,0.065420,0.005993,0.005216,0.005492,0.005747,0.004183,0.005373,0.004388,0.005619,0.004121,...,72.0,1160180.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
134431,0.065421,0.005993,0.005216,0.005492,0.005747,0.004183,0.005373,0.004388,0.005617,0.004121,...,72.0,1160180.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
134432,0.142307,0.016379,0.010974,0.005991,0.009369,0.005670,0.003335,0.003099,0.009761,0.002385,...,64.0,674640.0,0.0,0.0,2180.0,585728.0,0.0,0.0,0.0,0.0
134433,0.142308,0.016379,0.010974,0.005991,0.009369,0.005670,0.003335,0.003099,0.009761,0.002386,...,64.0,674640.0,0.0,0.0,2180.0,585728.0,0.0,0.0,0.0,0.0
134434,0.142307,0.016379,0.010974,0.005991,0.009369,0.005670,0.003335,0.003099,0.009761,0.002385,...,64.0,674640.0,0.0,0.0,2180.0,585728.0,0.0,0.0,0.0,0.0

In [4]:
df2 = pd.DataFrame(y)

df2

        0
0       0
1       0
2       0
3       0
4       0
...    ..
134430  1
134431  1
134432  1
134433  1
134434  1

[134435 rows x 1 columns]

In [5]:
data1 = pd.read_csv("ember_2381_feature_names.txt", delimiter = "\t")

data1

                                          0
0                          ByteHistorgram-0
1                          ByteHistorgram-1
2                          ByteHistorgram-2
3                          ByteHistorgram-3
4                          ByteHistorgram-4
...                                     ...
2376  virtual size of data directories - 12
2377          size of data directories - 13
2378  virtual size of data directories - 13
2379          size of data directories - 14
2380  virtual size of data directories - 14

[2381 rows x 1 columns]

In [6]:
head = data1.T

head

,0,1,2,3,4,5,6,7,8,9,...,2371,2372,2373,2374,2375,2376,2377,2378,2379,2380
0,ByteHistorgram-0,ByteHistorgram-1,ByteHistorgram-2,ByteHistorgram-3,ByteHistorgram-4,ByteHistorgram-5,ByteHistorgram-6,ByteHistorgram-7,ByteHistorgram-8,ByteHistorgram-9,...,size of data directories - 10,virtual size of data directories - 10,size of data directories - 11,virtual size of data directories - 11,size of data directories - 12,virtual size of data directories - 12,size of data directories - 13,virtual size of data directories - 13,size of data directories - 14,virtual size of data directories - 14

# new_data = pd.concat([df1, data1.T], axis=1)    #merge dataframes

dataset = df1.append(head, ignore_index=True)        #freezing problem

In [7]:
dataset = df1.append(head, ignore_index=True)

In [8]:
dataset

,0,1,2,3,4,5,6,7,8,9,...,2371,2372,2373,2374,2375,2376,2377,2378,2379,2380
0,0.056742,0.008017,0.007762,0.005466,0.007762,0.004446,0.00543,0.003061,0.009475,0.006305,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.007062,0.0045,0.004498,0.004318,0.00441,0.00433,0.004265,0.004068,0.004391,0.004306,...,0.0,0.0,0.0,0.0,120.0,16564.0,0.0,0.0,0.0,0.0
2,0.020975,0.004699,0.004002,0.004419,0.004214,0.003865,0.003973,0.004297,0.003921,0.004145,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.006482,0.003821,0.003788,0.003866,0.003734,0.003784,0.003884,0.003937,0.003805,0.003809,...,0.0,0.0,0.0,0.0,140.0,16384.0,0.0,0.0,0.0,0.0
4,0.022135,0.003972,0.003834,0.003869,0.003759,0.003765,0.003777,0.003863,0.003773,0.003798,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134431,0.065421,0.005993,0.005216,0.005492,0.005747,0.004183,0.005373,0.004388,0.005617,0.004121,...,72.0,1160180.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
134432,0.142307,0.016379,0.010974,0.005991,0.009369,0.00567,0.003335,0.003099,0.009761,0.002385,...,64.0,674640.0,0.0,0.0,2180.0,585728.0,0.0,0.0,0.0,0.0
134433,0.142308,0.016379,0.010974,0.005991,0.009369,0.00567,0.003335,0.003099,0.009761,0.002386,...,64.0,674640.0,0.0,0.0,2180.0,585728.0,0.0,0.0,0.0,0.0
134434,0.142307,0.016379,0.010974,0.005991,0.009369,0.00567,0.003335,0.003099,0.009761,0.002385,...,64.0,674640.0,0.0,0.0,2180.0,585728.0,0.0,0.0,0.0,0.0
134435,ByteHistorgram-0,ByteHistorgram-1,ByteHistorgram-2,ByteHistorgram-3,ByteHistorgram-4,ByteHistorgram-5,ByteHistorgram-6,ByteHistorgram-7,ByteHistorgram-8,ByteHistorgram-9,...,size of data directories - 10,virtual size of data directories - 10,size of data directories - 11,virtual size of data directories - 11,size of data directories - 12,virtual size of data directories - 12,size of data directories - 13,virtual size of data directories - 13,size of data directories - 14,virtual size of data directories - 14

In [9]:
dataset.to_csv('dataset.csv')

In [ ]:
test = pd.read_csv('dataset.csv')

In [ ]:
test